### ISSUE TITLE
Bless You !

### ISSUE THREAD

**Issue by gavineadie** [davedelong/time#17]
Not an 'issue', as such, so feel free to mark closed.  Time is difficult, as you note, and my first time-related challenge in the iOS world was that, in the early days, the "wall clock" could be off true by up to two minutes.  With a satellite tracking app in work, that was going to make life complicated; at 7Km/s, 100 seconds could be the wrong side of the sky!

My solution was to write and embed a simple Simple Network Time Protocol (SNTP) client in my app .. it wasn't nearly as rigorous as the NTP reference code, but it gave me sub-second accuracy.  At some point in the evolution of iOS, NTP was adopted and "wall clock" became useful (typically, my iPhone's "wall clock" can be trusted to be within a few microseconds).

I lobbied for a while, at WWDCs and via Radar, for a Time analog to Location .. a CoreTime framework for example, that offered, among other things, an 'accuracy' negotiation.  Your work here is aimed at a different target in the 'time' domain, nevertheless I'm excited .. I see things I will put to immediate use.  Thank you, Dave.

**Comment by davedelong** [comment]
You're welcome! 🤗
