### ISSUE TITLE
Feature: Clock "chimes"

### ISSUE THREAD

**Issue by davedelong** [davedelong/time#18]
It'd be nice to add a way for a `Clock` to notify you about significant time changes, like how clocks chime in the real world.

There are a couple API scenarios to consider:
- starting from a provided `Value`, notify me every time this `Difference` has elapsed 
- starting from now, notify me every time this `SISecond`/`Difference` has elapsed
- starting from now, notify me every time a value matching these `DateComponents` occurs

There will be some interesting challenges when it comes to clocks that scale time (ie, run slower or faster than real time).

**Comment by davedelong** [comment]
One the relative API goes in, this will apply as well:
- starting from now (or a provided `Value`), notify me every time it matches this provided relative value.

**Comment by davedelong** [comment]
One thought is that it might be interesting to return an _object_ from this registration method that is a SwiftUI `ObservableObject`... (assuming `canImport(SwiftUI)`)

That way you could get one of these and then use it to automatically power a `SwiftUI` view that derives its value from the current `Clock` state. This would allow you to construct views that update at different "chiming" intervals, all based on the same Clock.

**Comment by AverageHelper** [comment]
I think `ObservableObject` is a `Combine` protocol.  But otherwise I really like this idea!  It saves me having to set a `Timer` publisher to constantly "glance" back at the `clock`. 😊

**Comment by AverageHelper** [comment]
Would something like `DispatchQueue`'s `asyncAfter(deadline:)` method work to publish at the right time?  Since we can already treat the raw value of `SISeconds` as `TimeInterval` values, this might work nicely.  As for clocks which scale those seconds, if I understand rightly we should only need to multiply the value we feed `Dispatch` by the clock's scale factor.

In reference to your third case, "starting from now, notify me every time a value matching these DateComponents occurs," I suppose we would ignore temporal moments that have already elapsed, or moments occurring between app executions. That seems like something complex enough for client projects to implement themselves. (Unless you have something else in mind?)

**Comment by davedelong** [comment]
I think a `Foundation.Timer` or a `DispatchSourceTimer` would be better than an `asyncAfter(...)` call, mainly because you get more control over starting and stopping.

Also, it'd be nice to have a `.publisher(...)` method on `Clock` as well to expose this.

**Comment by AverageHelper** [comment]
That would. Ideally, I'd like to think of the `Clock` itself as a publisher, since that's what we look to for time in real life, but API wise, a `publisher(...)` method would make sense.

Maybe something like `clock.publisher(forChimeInterval: someDifference)`.

**Comment by AverageHelper** [comment]
The API would depend on how closely we want to mirror the real-life clock interface. It makes sense to me that we would also publish on `NSNotificationCenter` when the Clock chimes, as though an observer is listening from another room and cannot see the clock closely (has no reference to the clock itself). With this idiom, somehow setting chime intervals on the `Clock` instance itself makes sense.

Perhaps we might expose a `setChimeInterval(someDifference, from: someValue)` instance method on the clock, which would set the clock's chime interval offset by a certain time.  For example, it may be useful to set a chime interval every half hour, starting at the top of the hour (as opposed to the instant when the chime is set, which may be anytime).

**Comment by davedelong** [comment]
> But if we would depart a little from real-life clocks, a method that returns some `Combine.Publisher` would work just fine on its own.

I think this would be the way to go. I like the idea of having multiple kinds of observations on a single clock. One part of an app might only want "significant" (once a day) chimes, but another part might want sub-second chimes. It'd be nice to support all of those from the same `Clock` instance.

**Comment by AverageHelper** [comment]
As for waiting for specific times to occur, a separate API interface would make sense.

Perhaps `.publisher(for: someAbsoluteValue)`, or if we're going with the `Clock` or a `Clock.Bell` being the actual `Publisher`, we might call `setAlarm(for: someAbsoluteValue)` on the `Clock`.

**Comment by davedelong** [comment]
I'm thinking...
```swift
extension Clock {
    // set up a repeating chime (ex: "every 5 minutes")
    // use the "starting from" parameter to specify the start point for chimes. 
    // if "starting from" is nil, then it starts chiming relative to the current time
    func chime(every interval: Difference<...>, starting from: Absolute<...>? = nil) → Clock.Publisher

    // set up a repeating chime that only chimes when the current time matches the passed-in closure
    // ex: clock.chime(when: { (time: Absolute<Minute> in return time.minute % 13 == 0 })
    // chimes at *:00, *:13, *:26, *:39, *:52
    func chime(when matches: @escaping (Absolute<...>) -> Bool) → Clock.Publisher

    // chimes at most once and then completes
    // useful for "tell me when it's 3:00 PM"
    func chime(at time: Absolute<...>) -> Clock.Publisher
}
```

**Comment by AverageHelper** [comment]
I'll get cracking on something like that, and make a PR, if you'd like. I'm excited to give it a try!

**Comment by davedelong** [comment]
`chime(when matches:)` can be trivially implemented in terms of `chime(every interval:)`:

```func chime<U: Unit>(when matches: @escaping (Absolute<U>) → Bool) → AnyPublisher<Absolute<U>> {
    let startTime: Absolute<U> = self.this()
    let interval: Difference<U, Era> = Difference(value: 1, unit: U.component)
    return chime(every: interval, starting: startTime).filter(matches).eraseToAnyPublisher()
}```

**Comment by AverageHelper** [comment]
Created PR (#41). If I'm reading the checks report right, it looks like there have been some API changes today.  I'll look into pulling those into my fork tomorrow.
