### ISSUE TITLE
Usage of "Unsafe"

### ISSUE THREAD

**Issue by davedelong** [davedelong/time#20]
The [discussion on the Swift Forums](https://forums.swift.org/t/introducing-time/34196) brought up some objections to the usage of `unsafe` in the APIs:

```swift
init(region: Region, unsafeDateComponents: DateComponents) throws

struct UnsafeAdjustment<...> {
    // ...
}
```

The primary objection is that "unsafe" is used exclusively in the standard library to refer to memory safety issues, and that having a method declared with `throws` is *enough indication* that something can go wrong.

@belkadan [brought up this point](https://forums.swift.org/t/introducing-time/34196/27):
> "Unsafe" is not supposed to mean "has preconditions which are the client's responsibility". In a narrow form, it would be "can break type safety, memory safety, or exhaustivity" (because breaking any one can lead to the others breaking), but if you were to make an argument for a broader form, I would say it would be "may corrupt data if you break the preconditions", which Time's usage is almost the opposite of.

These are all valid points.

---

I'm open to changing the usage of "Unsafe" in `Time`, but here are some thoughts to consider:

- `Unsafe` is used for more than just a name in an initializer parameter; it's also used as the name of a type (currently internal, but will be public): `UnsafeAdjustment`

- Given the two broad categories of adjustments, using the term `Unsafe` has been nice, because it has a clear and familiar antonym of `Safe`. I'd prefer any replacement word to also have a clear antonym, to maintain the strong pairing between "safe" and "unsafe" adjustments.

- Any alternative would ideally be succinct, as dealing with `MightPossiblyFailAdjustment` in code would be tiresome and aesthetically unpleasing.

- `Time` is not part of the standard library, thus it is not bound by the standard library's style and conventions. 

- "Unsafe" is a term *familiar* to Swift developers, even beyond the explicit context of "memory safety"

**Comment by davedelong** [comment]
Some alternatives that I've considered:

- `Unchecked` (not accurate, because the results are checked)
- `Raw` (no good antonym)
- `Unstable` (ok, but would be a large departure from current [un]stable usage, in relation to sorting)
- `Arbitrary` (no clear antonym)

**Comment by Lantua** [comment]
Also
- `Failable`

Another interesting one would be to do both of these:
- move `UnsafeAdjustment` ~> `Adjustment`, and
- move `Adjustment` ~> `GuaranteedAdjustment`.

**Comment by davedelong** [comment]
The term `strict` has been growing on me recently.

**Comment by davedelong** [comment]
`strict` would also match the API in `NSCalendar`'s `MatchingPolicy`, which would be appropriate...

I think I'll go with that.
