### ISSUE TITLE
Examples: iOS App

### ISSUE THREAD

**Issue by davedelong** [davedelong/time#24]
I'd like an `/Examples` folder with some simple iOS apps showing how to use `Time`.

The first one that comes to mind is a basic iOS app using a `UICollectionView` to build a month calendar view.

**Comment by TiagoMaiaL** [comment]
@davedelong  Could this app be written with SwiftUI? I'd like to work on this.

**Comment by davedelong** [comment]
@TiagoMaiaL sure!

**Comment by jalurgemilang** [comment]
Is there a way to download this Example app that was written in SwiftUI @TiagoMaiaL please?

**Comment by davedelong** [comment]
There's an `Examples` folder with an Xcode project with a couple small samples now. I'll close this as completed, and we can open new issues for specific desired examples.
