### ISSUE TITLE
Time from String

### ISSUE THREAD

**Issue by xiaoxidong** [davedelong/time#25]
Hi, can I get a time from a string?

**Comment by elitalon** [comment]
@xiaoxidong You can parse `Absolute` values from strings using the convenience initialisers defined in [`Absolute+Parsing.swift`](https://github.com/davedelong/time/blob/c39a8a7d40d02e56f060b301d00e5eeb6e42b0ed/Sources/Time/Parsing/Absolute%2BParsing.swift), for example:

```swift
do {
    let value = try Absolute<Day>(stringValue: "03-14-2020",
                                  region: .current,
                                  year: .full,
                                  month: .twoDigits,
                                  day: .twoDigits)
    print(value) // Saturday, March 14, 2020, GMT+1
} catch {
    print(error)
}
```

If I understood it correctly, additional support for parsing is also included in the lists of [short-term features](https://github.com/davedelong/time/blob/master/Documentation/1-Overview/2-Roadmap.md#short-term-features) and [long-term features](https://github.com/davedelong/time/blob/master/Documentation/1-Overview/2-Roadmap.md#long-term-features) of `Time`.

**Comment by davedelong** [comment]
Yes, those will definitely work for parsing time strings. I'll be adding another initializer soon to provide an explicit format string as well (such as `MMMM d 'at' h:mm a`).
