### ISSUE TITLE
Initializing an Absolute<U> without an explicit era always throws

### ISSUE THREAD

**Issue by sadlerjw** [davedelong/time#27]
```swift
try! Absolute<Day>(region: .posix, year: 2019, month: 10, day: 14)
```
always throws because in `Time.Calendar.exactDate(from:, matching:)`, `restricted` does not include a value for `era`, but `proposedComponents` has `era` set to `1`, so `guard proposedComponents == restricted` fails.

Of course this isn't a big deal because I only use this initializer in my test target and I can easily add the era, but the API suggests it should work, since in the initializer `era` is an Optional and defaults to `nil`.

If I knew the correct fix I'd submit a PR...maybe this works?
```swift
var restrictedWithEra = restricted
if restrictedWithEra.era == nil && !isEraRelevant {
    restrictedWithEra.era = proposed.era
}

guard proposedComponents == restrictedWithEra.era else {
    throw AdjustmentError.invalidDateComponents(restricted)
}
```

BTW this library is everything I never knew I wanted. Thank you! 😄

**Comment by davedelong** [comment]
Great catch! Thanks for pointing this out.
