### ISSUE TITLE
Allen's interval algebra

### ISSUE THREAD

**Issue by michaellenaghan** [davedelong/time#29]
You've probably come across this, but just in case you haven't: 

> Allen's interval algebra is a calculus for temporal reasoning that was introduced by James F. Allen in 1983.
> 
> The calculus defines possible relations between time intervals and provides a composition table that can be used as a basis for reasoning about temporal descriptions of events.
> 

There's a Wikipedia summary [here](https://en.wikipedia.org/wiki/Allen%27s_interval_algebra). Allen's original paper, *Maintaining knowledge about temporal intervals*, is [here](http://cse.unl.edu/~choueiry/Documents/Allen-CACM1983.pdf). I first heard about it in [this](https://www.youtube.com/watch?v=T29WzvaPNc8) talk, *Modelling Time*, by Eric Evans (the Domain-Driven Design guy).

Even if all of this is outside of the scope of what you're trying to do it seems like it might be a useful thing to be aware of. Just, you know, in case. :-)

**Comment by davedelong** [comment]
This is fantastic stuff, thank you!

The interval algebra will fit in perfectly with determining the relation between values.
