### ISSUE TITLE
Document SISeconds

### ISSUE THREAD

**Issue by davedelong** [davedelong/time#3]

**Comment by samkrishna** [comment]
Is `SI` an *intended* abbreviation for *System Internationale*?

**Comment by marvin-yorke** [comment]
Yes, see https://github.com/davedelong/Chronology/blob/221d525d2844a505e6a88998f346656f6dcdd876/Sources/Chronology/Calendar.swift#L14

**Comment by samkrishna** [comment]
Thanks for pointing that out. Now I know how to think about some future tests.
