### ISSUE TITLE
Custom Formatting

### ISSUE THREAD

**Issue by alexjameslittle** [davedelong/time#38]
I would like to have more control over the formatting of the absolute value. For example I would like to get the day of the week. I would usually just use "E" as a date format in order to get the first letter of the day of the week. However it appears that `Template` initialisers are internal and therefore unable to use a custom format. What would you suggest in this scenario?

**Comment by davedelong** [comment]
`E` is the same thing as `eee`, so you can do:

```swift
let today = Clock.system.today()

let abbreviatedWeekdayName = today.format(weekday: .abbreviatedName) // ex: "Sat"
let fullWeekdayName = today.format(weekday: .fullName) // ex: "Saturday"
let narrowWeekdayName = today.format(weekday: .narrowName) // ex: "S"
let shortWeekdayName = today.format(weekday: .shortName) // ex: "Sa"
```

**Comment by alexjameslittle** [comment]
That's correct however the format functions force you to pass a format for the era, year, month etc. You can't just use the weekday format.
