### ISSUE TITLE
Force formatting order

### ISSUE THREAD

**Issue by alexito4** [davedelong/time#39]
I have a `Absolute<Day>` and would like to get a string like `2018-05-11`, no matter the user setting (the usage is for file output, not UI). Is there a way to accomplish this?
The `format(year: , month: ., day:)` seems to always use a style like `3/27/20` (note the order and the `/`). I've tried changing the locale of the date itself but doesn't seem to have any effect.

**Comment by davedelong** [comment]
Yeah, this is definitely a deficiency. I'm working on a way to format a time value with an explicit format string.
