### ISSUE TITLE
Infinite loop in `Absolute.range`

### ISSUE THREAD

**Issue by trispo** [davedelong/time#44]
Hi,

I'm looking for a way to check, whether a previous call to my networking api was sent more than 5 minutes ago. I thought trying your project for this would be a nice start. On first launch, there was now call at all so I usually use `Foundation.Date.distantPast`. I ended with the following code ...

```swift
let now = Clock.system.thisMinute()
let lastUpdate = Absolute<Minute>(region: .current, instant: .init(date: .distantPast))

let differenceSinceLastUpdate = now - lastUpdate

guard differenceSinceLastUpdate.minutes > 5 else { return }
```

... and found that it is ending in an infinite loop in `Absolute.range`.

Here my questions:

1. Is this the right way to solve my issue?
2. Is this infinite loop a known bug?

Thanks in advance.

**Comment by davedelong** [comment]
Hi @trispo! If you’re currently pointed at the `0.9.0` tag, try switching to the `master` branch. There was an infinite recursion bug between `.range` and `.approximateMidPoint` that has been fixed. (See #19)

**Comment by trispo** [comment]
Hi @davedelong! Thanks, I missed this issue. I will open a new issue regarding my first question.
