### ISSUE TITLE
How to ask whether an event is more than n minutes ago?

### ISSUE THREAD

**Issue by trispo** [davedelong/time#45]
Hi,

I'm looking for a way to check, whether a previous call to my networking api was sent more than 5 minutes ago. I thought trying your project for this would be a nice start. On first launch, there was now call at all so I usually use `Foundation.Date.distantPast`. I ended with the following code ...

```swift
let now = Clock.system.thisMinute()
let lastUpdate = Absolute<Minute>(region: .current, instant: .init(date: .distantPast))

let differenceSinceLastUpdate = now - lastUpdate

guard differenceSinceLastUpdate.minutes > 5 else { return }
```

... but this seems to be wrong as `differenceSinceLastUpdate.minutes` is not the value I expected it to be.

What is the right way to get the number of minutes between two dates?

**Comment by davedelong** [comment]
Hi @trispo! The method you're looking for in 1.0 is called [`Fixed.differenceInWholeMinutes(to:)`](https://swiftpackageindex.com/davedelong/time/1.0.0/documentation/time/fixed/differenceinwholeminutes(to:)). That will give you a difference between two fixed values that is _only_ in minutes.
