### ISSUE TITLE
Slow initialisation

### ISSUE THREAD

**Issue by alexjameslittle** [davedelong/time#50]
When initialising an Absolute TimePeriod we are seeing very slow performance. It is taking 90ms+ to initialise a time period. Also getting bad performance when trying to add or subtract from time periods. Please see the attached image of the time profile I ran which leads me to the TimePeriod initialiser and the subtracting of time period.

<img width="1205" alt="Screenshot 2020-06-23 at 13 13 11" src="https://user-images.githubusercontent.com/25927944/85402632-e78e5800-b553-11ea-9299-ccc69d560561.png">

**Comment by davedelong** [comment]
@alexjameslittle the code path referenced in your screenshot no longer exists. Are you still having issues with initialization times?

**Comment by alexjameslittle** [comment]
It's been a while since we used this library so it's probably best to close this issue
