### ISSUE TITLE
Make Template.template public

### ISSUE THREAD

**Issue by Robuske** [davedelong/time#53]
Hello, first of all, thank you for all your work on this library.

Apart from that, the title says it all, would be nice to be able to use `Template` values for raw formatting/parsing. I thought about making a micro PR, but I feared there was a reason for it not being public, besides it's a change so small that you could make trough Github edit.

P.S.: Am I missing something or is it not possible to parse a date with the format `y-MM-dd` without using the `rawFormat`? I thought that using the `iso8601` `Calendar` would work, but it does not seem to be the case.

**Comment by davedelong** [comment]
On the parsing side, `Fixed` has an initializer that takes [a string and a hard-coded format string](https://swiftpackageindex.com/davedelong/time/1.0.0/documentation/time/fixed/init%28stringvalue:rawformat:region:%29)

For formatting, there's a [`.format(raw:)`](https://swiftpackageindex.com/davedelong/time/1.0.0/documentation/time/fixed/format(raw:strict:)) method to which you can pass a hard-coded format string.
