### ISSUE TITLE
Add total unit values to TimeDifference

### ISSUE THREAD

**Issue by Mordil** [davedelong/time#57]
Right now `TimeDifference` provides concrete `Int` properties of each unit component of a given difference, which leaves users to implement a way of getting a total of a specific unit.

For example, to find the total number of minutes between two TimePeriods (such as an event with a start/end), you need to do:

```swift
difference.hours * 60 + difference.minutes
```

I'd be appreciative to have an API like the following:
```swift
extension TimeDifference {
  func total(_ unit: Calendar.Component) -> Double
}

let diff = start - end // hour: 1 minute: 3

print(diff.total(.minute))
// 63
print(diff.total(.hour))
// 1.05
```

I understand this can get very problematic at higher & lower precision, maybe a first release could just be seconds/minutes/hours?

**Comment by davedelong** [comment]
I'm not sure this is entirely possible at the `TimeDifference` level… How would `TimeDifference` know if one of the intermediate hours was longer or shorter than normal?

**Comment by Mordil** [comment]
I think the 2nd API call is more of exactly what I was looking for, for the original use case
